/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import connection.ConnectionDB;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.ComponentOrientation;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.LayoutStyle;
import model.bean.UsuarioDTO;
import model.dao.QuartosDAO;
import model.dao.UsuarioDAO;
import model.bean.Quartos;
import javax.swing.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import model.bean.AluguelDTO;
import model.dao.AluguelDAO;
import timer.horas;
import timer.minuto;
import timer.segundo;
/**
 *
 * @author estev
 */
public class Telaprincipal extends javax.swing.JFrame {

    private Boolean toggle = true;
    Connection conn;
    ResultSet rs = null;
    PreparedStatement pstm;
    segundo segundo;
    minuto minuto;
    horas horas;
    Thread tseg,tmin,thora;
    ModeloQuarto lbl;
    
            
    /**
     * Creates new form Telaprincipal
     */
    public Telaprincipal() {
        initComponents();
        iniciarGridLayout();
        
        //iniciando os componentes
        
       
       }
    
    public void timer(){
        ///tentativa de fazer um timer
        segundo = new segundo();
        minuto = new minuto();
        horas = new horas();
        
        tseg = new Thread(segundo);
        tmin = new Thread(minuto);
        thora = new Thread(horas);
        
        tseg.start();
        tmin.start();
        thora.start();
    
    }
    public final void iniciarGridLayout(){
         QuartosDAO qDAO = new QuartosDAO();     
         //JPQRT É O ID DO GRIDLAYOUT
         JPQrt.setLayout(new GridLayout(4,5,10,10));
        for (Quartos q : qDAO.read()){
            //LBL É A JLABEL RESPONSÁVEL POR MOSTRAR AS INFORMAÇÕES DOS QUARTOS
            lbl = new ModeloQuarto();
            ModeloQuarto.txtNumero.setText(q.getNumeroQuarto());
            ModeloQuarto.tpQuarto.setText(q.getNomeQuarto());
            ModeloQuarto.txtStatus.setText(q.getStatus());
            //AQUI MOSTRA TODAS AS INFORMAÇÕES DOS QUARTOS
            if("DISPONIVEL".equals(q.getStatus())){
                lbl.setBackground(new Color(255,255,255));
            }
            if("ALUGADO".equals(q.getStatus())){
                timer();
                lbl.setBackground(Color.red);
            }
            JPQrt.add(lbl);
            
            lbl.addMouseListener(new MouseAdapter() {
                @Override
                
                public void mouseClicked(MouseEvent event) {
                    super.mouseClicked(event);
                        jLabel3.setText(q.getNomeQuarto());
                        txtNrm2.setText(q.getNumeroQuarto());
                        btnInit.setEnabled(true);     
                        
                        
                }       
            });
            
            
        
        }
        
    }
    
    
    public void exportarInformacao (UsuarioDTO user){
        
        txtUser.setText(user.getLogin());
        conn = new ConnectionDB().conectaDB();
        
        String sql = "Select * from usuarios WHERE login = ?";
        try {
            pstm = conn.prepareCall(sql);
            pstm.setString(1, user.getLogin());
            rs = pstm.executeQuery();
            if(rs.next()){
                txtNome.setText(rs.getString("nome"));
                txtCargo.setText(rs.getString("tipo_user"));
                if(!rs.getString("tipo_user").equals("ADMINISTRADOR")){
                    jButton5.setEnabled(false);
                    btnEstoque.setEnabled(false);
                    jButton7.setEnabled(false);
                } 
            }
            pstm.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar informações de Usuario"+ e);
            
        }
        
    }
    
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastro = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNrm2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        btnFin = new java.awt.Button();
        btnInit = new java.awt.Button();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        JPQrt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new javax.swing.JLabel();
        txtCargo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Keros Motel 1.0.0");
        setBackground(new java.awt.Color(255, 255, 255));

        btnCadastro.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfil-de-usuario.png"))); // NOI18N
        btnCadastro.setBorder(null);
        btnCadastro.setBorderPainted(false);
        btnCadastro.setPreferredSize(new java.awt.Dimension(60, 60));
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quarto.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnEstoque.setBackground(new java.awt.Color(255, 255, 255));
        btnEstoque.setForeground(new java.awt.Color(255, 255, 255));
        btnEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/estoque.png"))); // NOI18N
        btnEstoque.setBorder(null);
        btnEstoque.setBorderPainted(false);
        btnEstoque.setPreferredSize(new java.awt.Dimension(60, 60));
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setPreferredSize(new java.awt.Dimension(60, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(250, 255, 255));

        jCalendar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCalendar1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N

        jLabel1.setText("INFORMAÇÕES DO QUARTO");

        jLabel3.setText("S/I");

        txtNrm2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtNrm2.setText("S/I");

        jLabel7.setText("QUARTO NUMEROº :");

        jLabel8.setText("TIPO QUARTO:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUTO", "PREÇO", "QUANTIDADE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setText("CONSUMO ATUAL:");

        btnFin.setBackground(new java.awt.Color(255, 51, 51));
        btnFin.setEnabled(false);
        btnFin.setLabel("FINALIZAR");
        btnFin.setName(""); // NOI18N
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });

        btnInit.setBackground(new java.awt.Color(51, 255, 51));
        btnInit.setEnabled(false);
        btnInit.setLabel("INICIAR");
        btnInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitActionPerformed(evt);
            }
        });

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("APAGAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnInit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNrm2)
                                    .addComponent(jLabel3))))
                        .addGap(0, 218, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jCalendar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNrm2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(btnInit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnFin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPQrt.setBackground(new java.awt.Color(255, 255, 255));
        JPQrt.setBorder(javax.swing.BorderFactory.createTitledBorder("QUARTOS"));
        JPQrt.setForeground(new java.awt.Color(255, 255, 255));
        JPQrt.setMaximumSize(new java.awt.Dimension(735, 560));
        JPQrt.setMinimumSize(new java.awt.Dimension(735, 560));
        JPQrt.setPreferredSize(new java.awt.Dimension(735, 560));
        JPQrt.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Nome:");

        txtNome.setText("jLabel3");

        jLabel4.setText("Cargo:");

        jLabel5.setText("Usuario:");

        txtUser.setText("jLabel6");

        txtCargo.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCargo)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUser))))
                    .addComponent(JPQrt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txtUser))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtCargo)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPQrt, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cadastrarAlug(){
       
       
        String numeroQuarto, clientes, funcionario1, funcionario2, tppagamento;
        numeroQuarto = txtNrm2.getText();
        clientes = "genivaldo";
        funcionario1 = txtNome.getText();
        funcionario2 = "";
        tppagamento = "";
        AluguelDTO alugDTO = new AluguelDTO();
        
        alugDTO.setNome(numeroQuarto);
        alugDTO.setFuncionario1(funcionario1);
        alugDTO.setTpPagamento(tppagamento);
        alugDTO.setFuncionario2(funcionario2);
        alugDTO.setClientes(clientes);
        
        AluguelDAO dao = new AluguelDAO();
        dao.cadastrarAluguel(alugDTO);
        
        Quartos q = new Quartos();
        QuartosDAO qDAO = new QuartosDAO();
        q.setStatus("ALUGADO");
        q.setNumeroQuarto(numeroQuarto);
        qDAO.mudarStatus(q);
        
        
        JPQrt.removeAll();
        JPQrt.revalidate();
        JPQrt.repaint();
        
        iniciarGridLayout();
    }
    public void testarBotoes(){

    }
    
    public void finalizarAlug(){}
    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
        new painelCadastro2().setVisible(true);
        
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new cadastroQuarto().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        // TODO add your handling code here:
        new telaEstoque().setVisible(true);
    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void btnInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitActionPerformed
          // TODO add your handling code here:
        cadastrarAlug();
        testarBotoes();
    }//GEN-LAST:event_btnInitActionPerformed

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
        // TODO add your handling code here:
        finalizarAlug();
        testarBotoes();
    }//GEN-LAST:event_btnFinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String item = JOptionPane.showInputDialog("Numero do Item");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telaprincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPQrt;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnEstoque;
    private java.awt.Button btnFin;
    private java.awt.Button btnInit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtCargo;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtNrm2;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
